# Generated by Django 2.1.3 on 2020-04-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nodeinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='主机名')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('province', models.CharField(max_length=32, verbose_name='省份')),
                ('city', models.CharField(max_length=32, verbose_name='城市')),
                ('isp', models.CharField(max_length=32, verbose_name='代理商')),
                ('machineagent', models.CharField(max_length=32, verbose_name='代理商')),
                ('vip', models.GenericIPAddressField(blank=True, null=True, verbose_name='VIP地址')),
            ],
        ),
    ]
