# Generated by Django 2.1.3 on 2020-04-15 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cdn', '0002_nodeinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodeinfo',
            name='isp',
            field=models.CharField(max_length=32, verbose_name='运营商'),
        ),
    ]
